api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'API Recettes'
    description: 'De belles recettes délicieuses !'
    version: '0.0.1'
    show_webby: false